version: "3.8"

networks:
  compose_monitor_net:
    external: true

services:
  api:
    image: iamdudumon/my-nest-app
    ports:
      - "${API_PORT:-3000}:3000"
    env_file: .env
    deploy:
      resources:
        limits:
          cpus: "${CPU:-1.0}"
          memory: "${MEM:-1024M}"
        reservations:
          cpus: "0.5"
          memory: 512M
    networks:
      - compose_monitor_net

  k6:
    image: grafana/k6
    depends_on:
      - api
    volumes:
      - ./testharness/:/src
    entrypoint: ["sh", "-c"]
    command:
      - >
        until wget --quiet --spider http://api:3000/boards; do
          echo 'waiting for api…'; sleep 1;
        done;
        k6 run -o experimental-prometheus-rw /src/k6_script.test.ts
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - JOB_ID=${JOB_ID}
      - EXP_ID=${EXP_ID}
    networks:
      - compose_monitor_net
