version: "3.8"

services:
  api:
    image: ${TEST_API_IMAGE}
    depends_on:
      - postgres
    env_file: .env
    cpus: "${CPU:-1.0}"
    mem_limit: "${MEM:-1024M}"
    memswap_limit: "${MEM:-1024M}"   # 스왑 금지 (mem==memswap)
    networks:
      - default

  postgres:
    image: postgres
    env_file: .env
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - "postgres_data:/var/lib/postgresql/data"
    cpus: 0.5
    mem_limit: 512M
    memswap_limit: 512M
    blkio_config:
      weight: 500
      device_read_bps:
        - path: /dev/sda
          rate: "50mb"
      device_write_bps:
        - path: /dev/sda
          rate: "20mb"
    networks:
      - default

  k6:
    image: grafana/k6
    depends_on:
      - api
    volumes:
      - ./testharness/:/src
    cpus: 0.5
    mem_limit: 256M
    memswap_limit: 256M
    entrypoint: ["sh", "-c"]
    command:
      - >
        k6 run -o experimental-prometheus-rw /src/k6_script.test.js
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
      - HTTP_REQ_DURATION=${HTTP_REQ_DURATION:-3000}
      - HTTP_REQS=${HTTP_REQS:-1000}
      - JOB_ID=${JOB_ID}
      - EXP_ID=${EXP_ID}
    networks:
      - default
      - compose_monitor_net

networks:
  compose_monitor_net:
    external: true

volumes:
  postgres_data:
    name: "postgres_data_${JOB_ID:?JOB_ID_not_set}"
